cmap_path: data/cmap/iron_colormap_rgb.txt
logging:
    version: 1
    formatters:
        basic:
            format: "[%(asctime)s][%(levelname)s] %(name)s:L%(lineno)d %(message)s"
        message:
            format: "%(message)s"
    handlers:
        file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: basic
            filename: .log
            encoding: UTF-8-sig
            maxBytes: 102400
            backupCount: 1
    root:
        level: INFO
        handlers:
            - file_handler
